### ISSUE TITLE
ESM version

### ISSUE THREAD

**Issue by bkawk** [EOSIO/ual-plainjs-renderer#26]
Would it be possible to provide an ESM version of the package?

`Uncaught SyntaxError: The requested module '../ual-plainjs-renderer/dist/index.js' does not provide an export named 'UALJs'`

Transpiling with Webpack does work for lynx but fails with Scatter 

`
ERROR in ./node_modules/scatterjs-core/dist/services/SocketService.js
Module not found: Error: Can't resolve '@babel/runtime/helpers/typeof' in '/Users/bkawk/Documents/eos-ual/node_modules/scatterjs-core/dist/services'
 @ ./node_modules/scatterjs-core/dist/services/SocketService.js 1:214-254
 @ ./node_modules/scatterjs-core/dist/index.js
 @ ./node_modules/ual-scatter/dist/Scatter.js
 @ ./node_modules/ual-scatter/dist/index.js
 @ ./index.js
`

**Comment by GreenBusDriver** [comment]
@bkawk I'll likely dig into this a bit more shortly, but I'm wondering if you had a chance to try [`esm` package](https://github.com/standard-things/esm) yet as featured in (this article](https://dev.to/bennypowers/you-should-be-using-esm-kn3#esm-a-better-solution)

**Comment by jlamarr22** [comment]
Confirmed `esm` package works with this repo's latest code.
