### ISSUE TITLE
[feature-request] A more stripped down or customizable plain js renderer

### ISSUE THREAD

**Issue by laurensV** [EOSIO/ual-plainjs-renderer#32]
It would be great if there was also a renderer that is either better customizable (auto show popup, customize text in popup/button, customize session settings etc.) or even better might be a version that just renders the links to the different authenticators, that still includes features like auto-login with sessions and logout etc. That way people have more control over when and how they want to render the links to the authenticators (maybe you don't want to use a popup, but just directly render the authenticator links without clicking a button for example).

**Comment by chris-allnutt** [comment]
@laurensV for now if you like you can look at taking the base and altering parts of the componentry if you look in here:  https://github.com/EOSIO/ual-plainjs-renderer/blob/master/src/UALJsDom.ts

You can see that we tried to componentize as much of the framework as possible.  Pieces of this could be taken and rewired into a simpler version.  Or pieces could be taken directly.
