### ISSUE TITLE
Allows for the same account to fill the users array many times.

### ISSUE THREAD

**Issue by nsjames** [EOSIO/ual-plainjs-renderer#49]
![image](https://user-images.githubusercontent.com/10360675/59851777-25bbcf00-9376-11e9-9494-e233cae6c7c4.png)

It seems if the login button isn't hidden then the same account will be pushed into the returned users array infinitely every time you sucessfully login.

**Comment by chris-allnutt** [comment]
@nsjames nice catch

**Comment by chris-allnutt** [comment]
Will be resolved in https://github.com/EOSIO/ual-scatter/pull/44 this is not a renderer bug, as described above.  If there is an error specific to the renderer we can address it in another ticket.
